node_js:
  - "node"

sudo: false

skip_cleanup: true

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache

install:
  - npm i -g yarn && yarn --ignore-engines

script:
  - yarn lint
  - yarn test:cover
